export const sample_foods=[
  {
    id: '1',
    name: 'Chicken Manchurian',
    decp:'Juicy Chicken Manchurian',
    price: 20,
    favorite: true,
    stars: 5,
    imageUrl: 'c1.png',
    category:'chicken',
  },
  {
    id: '2',
    name: 'Drumsticks',
    decp:'Chicken Drum Sticks',
    price: 30,
    favorite: true,
    stars: 5,
    imageUrl: 'c7.png',
    category:'chicken',
  },
  {
    id: '3',
    name: 'Butter paneer',
    decp:'Butter Paneer',
    price: 40,
    favorite: true,
    stars: 5,
    imageUrl: 'cu1.png',
    category:'curry',
  },
  {
    id: '4',
    name: 'Red Bull',
    decp:'Red Bull Energy Drink',
    price: 20,
    favorite: true,
    stars: 5,
    imageUrl: 'd1.png',
    category:'drinks',
  },
  {
    id: '5',
    name: 'Strawberries',
    decp:'Fresh Strawberries',
    price: 30,
    favorite: true,
    stars: 4.5,
    imageUrl: 'f1.png',
    category:'fruits',
  },
  {
    id: '6',
    name: 'Prawns Masala',
    decp:'Prawns Curry',
    price: 20,
    favorite: true,
    stars: 4,
    imageUrl: 'cu3.png',
    category:'curry',
  },
  {
    id: '7',
    name: 'Icecream',
    decp:'Chocolate & vanilla',
    price: 5.5,
    favorite: true,
    stars: 5,
    imageUrl: 'i1.png',
    category:'icecreams',
  },
]

  
  export const sample_users = [
    {
      id: 1,
      name: 'John Doe',
      email: 'john@gmail.com',
      password: '12345',
      address: 'Toronto On',
      isAdmin: false,
    },
    {
      id: 2,
      name: 'Jane Doe',
      email: 'jane@gmail.com',
      password: '12345',
      address: 'Shanghai',
      isAdmin: true,
    },
  ];